apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubernetes-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - joint.software
    secretName: todoapp-kubernetes-tls
  rules:
  - host: "joint.software"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: todoapp
            port:
              number: 80
