apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubernetes-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "joint.software"
    http:
      paths:
      - pathType: Prefix
        path: "/slava/"
        backend:
          service:
            name: todoapp
            port:
              number: 80
