apiVersion: v1
kind: Service
metadata:
  name: todoapp
spec:
  type: ClusterIP
  selector:
    app: todoapp
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8888
  externalTrafficPolicy: Local
