apiVersion: v1
kind: Service
metadata:
  name: todoapp
spec:
  type: LoadBalancer
  selector:
    app: todoapp
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  externalTrafficPolicy: Local
